### ISSUE TITLE
Output code is not compliant with Google Apps Script

### ISSUE THREAD

**Issue by cbaakel** [dreipol/babel-preset-google-apps-script#1]
Trying to convert "json-rules-engine" to Google Apps Script. Receiving an error

`typeof Symbol === 'function' && typeof Symbol.for === 'function'`
Using browserify.

package.json
```
{
  "name": "btso",
  "version": "1.0.0",
  "description": "",
  "main": "main.js",
  "scripts": {
    "test": "echo \"Error: no test specified\" && exit 1"
  },
  "author": "",
  "license": "ISC",
  "devDependencies": {
    "@babel/cli": "^7.8.3",
    "@babel/core": "^7.8.3",
    "@babel/preset-env": "^7.8.3",
    "@dreipol/babel-preset-google-apps-script": "^1.0.3",
    "babel-core": "^6.26.3",
    "babelify": "^10.0.0",
    "debug": "^4.1.1"
  },
  "dependencies": {
    "json-rules-engine": "^5.0.3",
    "selectn": "^1.1.2"
  },
  "browserify": {
    "transform": [["babelify", { "presets": [ "@dreipol/babel-preset-google-apps-script"] }]]
  }
}
```

Expected behavior: `Symbol.for` properly converted to Google Apps Script format

**Comment by nirazul** [comment]
Do you have a repository where I can reproduce the error?

There are things that are incompatible with GAS code and can't be translated. Especially built-ins like `Symbol` or `Promise` will never be usable in GAS without Google implementing it.

**Comment by cbaakel** [comment]
https://github.com/cbaakel/json-rules-to-gas

I've previously tried loading in the polyfills to no avail.

**Comment by nirazul** [comment]
As stated before, some modern features are impossible to convert to an older syntax (which GAS is based off). There are polyfills like `core-js` but there's no guarantee that your code can be converted.

**Comment by cbaakel** [comment]
GAS now updated, can disregard
